version: "3.8"

services:
  # web:
  #   container_name: web
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4173:4173
  #   restart: always
  #   environment:
  #     - VITE_FINKEPEER_URL=${FINKEPEER_URL}

  onchain_sui:
    container_name: onchain_sui
    build: onchain/sui/analytics/.
    ports:
      - "8080:8080"
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=${MONGO_URI}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  custom:
    driver: bridge
