# This file is for testing your build process, not for production
name: template-api
services:
  backend:
    build:
      dockerfile: ./Dockerfile
    container_name: template-api-backend
    restart: unless-stopped
    networks:
      - template-api-network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/test-api?schema=public

  db:
    image: postgres:alpine
    container_name: template-api-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-api
    networks:
      - template-api-network

networks:
  template-api-network:
    driver: bridge
